DIST_HEADER_MAPPING = {
    "Anchor": "anchor",
    "Data Received": "data_received",
    "Enrollment Date": "enrollment_date",
    "Distributor Code": "distributor_code",
    "Distributor Name": "distributor_name",
    "CFA Name":"cfa_name",
    "Region": "region",
    "Division": "division",
    "City": "city",
    "State": "state",
    "Pincode": "pincode",
    "Distribution Type":"distribution_type",
    "Leap/Non Leap":"leap_non_leap",
    "Email Id":"email",
    "Mobile No":"mobile_number",
    "Phone No":"phone_number",
    "GST Number":"gst_number",
    "PAN Number":"pan_number",
}

INVOICE_HEADER_MAPPING = {
    "Anchor": "anchor",
    "Processed by": "processed_by",
    "Working Date": "working_date",
    "Invoice Received Date": "invoice_received_date",
    "Received time": "received_time",
    "Loan type": "loan_type",
    "Lender Name": "lender_name",
    "Distributor Name": "distributor_name",
    "Distributor code": "distributor_code",
    "Contact Number": "contact_number",
    "Email ID": "email_id",
    "Himalaya CFA": "himalaya_cfa",
    "Beneficiary Name": "beneficiary_name",
    "Beneficiary A/c no": "beneficiary_a_c_no",
    "Bank Name": "bank_name",
    "IFSC Code": "ifsc_code",
    "Branch": "branch",
    "Invoice no": "invoice_no",
    "Invoice amount": "invoice_amount",
    "Invoice date": "invoice_date",
    "Loan Amount": "loan_amount",
    "Loan Disbursement date": "loan_disbursement_date",
    "Aging": "aging",
    "Tenure": "tenure",
    "UTR": "utr",
    "Status": "status",
    "Status Reason": "status_reason",
    "Comments": "comments",
}

KOTAK_HWC_TRANS_MAPPING = {
    "WCDL Account No": "wcdl_account_no",
    "Dealer Name": "dealer_name",
    "Total Limit": "total_limit",
    "Invoice Number": "invoice_number",
    "Reverse File Ref.": "reverse_file_ref",
    "Invoice Date(ID)": "invoice_date",
    "Disbursement date": "disbursement_date",
    "Tran/Value amount": "transaction_amount",
    "Balance Outstanding - INR": "balance_outstanding",
    "Due Date": "due_date",
    "Customer Payment Date": "customer_payment_date",
    "Overdue Within Cure - INR": "overdue_within_cure_amount",
    "Overdue Within Cure - No Of Days": "overdue_within_cure_days",
    "Overdue BeyondCure - INR": "overdue_beyond_cure_amount",
    "Overdue Beyond Cure - No Of Days": "overdue_beyond_cure_days",
    "Location": "location",
}

KOTAK_CKPL_TRANS_MAPPING = {
    "WCDL Account No": "wcdl_account_no",
    "Dealer Name": "dealer_name",
    "Total Limit": "total_limit",
    "Invoice Number": "invoice_number",
    "Invoice Date(ID)": "invoice_date_id",
    "Disbursement date": "disbursement_date",
    "Tran/Value amount": "tran_value_amount",
    "Balance Outstanding - INR": "balance_outstanding_inr",
    "Due Date": "due_date",
    "Customer Payment Date": "customer_payment_date",
    "Overdue Within Cure - INR": "overdue_within_cure_inr",
    "Overdue Within Cure - No Of Days": "overdue_within_cure_no_of_days",
    "Overdue BeyondCure - INR": "overdue_beyondcure_inr",
    "Overdue Beyond Cure - No Of Days": "overdue_beyond_cure_no_of_days",
    "Location": "location",
}

TCPL_TRANS_MAPPING = {
    "Customer ID": "customer_id",
    "Loan Account ID": "loan_account_id",
    "Customer Name": "customer_name",
    "Program ID": "program_id",
    "Program Name": "program_name",
    "Program Activation": "program_activation",
    "Program Expiry": "program_expiry",
    "Facility": "facility",
    "Financing": "financing",
    "Margin": "margin",
    "Drawdown Type": "drawdown_type",
    "Invoice No": "invoice_no",
    "Vehicle No": "vehicle_no",
    "Drawdown ID": "drawdown_id",
    "Loan Start Date": "loan_start_date",
    "Loan End Date": "loan_end_date",
    "Invoice Date": "invoice_date",
    "Tenure Days": "tenure_days",
    "Interest Type": "interest_type",
    "Interest Lock-in Date": "interest_lock_in_date",
    "Upfront Interest End Date": "upfront_interest_end_date",
    "Invoice Amount": "invoice_amount",
    "Drawdown Amount": "drawdown_amount",
    "Upfront Interest": "upfront_interest",
    "Holdback Amount": "holdback_amount",
    "Margin Amount": "margin_amount",
    "PF Amount": "pf_amount",
    "PF GST Amount": "pf_gst_amount",
    "Interest Rate": "interest_rate",
    "Loan Amount": "loan_amount",
    "Net Disbursed Amount": "net_disbursed_amount",
    "Principal Outstanding": "principal_outstanding",
    "Interest Outstanding": "interest_outstanding",
    "Accrued Interest": "accrued_interest",
    "Overdue Interest Outstanding": "overdue_interest_outstanding",
    "Penal Outstanding": "penal_outstanding",
    "Total Outstanding": "total_outstanding",
    "Principal Paid": "principal_paid",
    "Interest Paid": "interest_paid",
    "Overdue Paid": "overdue_paid",
    "Penal Paid": "penal_paid",
    "Total Repayment": "total_repayment",
    "Principal Waiver": "principal_waiver",
    "Interest Waiver": "interest_waiver",
    "Overdue Waiver": "overdue_waiver",
    "Penal Waiver": "penal_waiver",
    "GST Collected": "gst_collected",
    "GST Waived": "gst_waived",
    "Acknowledged Upfront Interest": "acknowledged_upfront_interest",
    "Remaining Upfront Interest": "remaining_upfront_interest",
    "Total Available Cashback": "total_available_cashback",
    "Adjusted Cashback": "adjusted_cashback",
    "Released Cashback": "released_cashback",
    "Total Holdback Cashback": "total_holdback_cashback",
    "Adjusted Holdback": "adjusted_holdback",
    "Released Holdback": "released_holdback",
    "Loan Status": "loan_status",
    "Closure Value Date": "closure_value_date",
    "Closure Transaction Date": "closure_transaction_date",
    "DPD": "dpd",
    "DPD RANGE": "dpd_range",
    "Max DPD in linked loan": "max_dpd_in_linked_loan",
    "Max DPD Range": "max_dpd_range",
    "Peak Delay": "peak_delay",
    "Asset_Categorization": "asset_categorization",
    "Asset Classification Date": "asset_classification_date",
    "Write-off Remark": "write_off_remark",
    "RM Name": "rm_name",
    "Corporate Code": "corporate_code",
    "Margin Received": "margin_received",
    "City": "city",
    "State": "state",
    "Pincode": "pincode",
    "Penal Tax Outstanding": "penal_tax_outstanding",
}

HERO_TRANS_MAPPING = {
    "SNO": "sno",
    "Client Name": "client_name",
    "Invoice Number": "invoice_number",
    "Invoice Date": "invoice_date",
    "Sanction Amount": "sanction_amount",
    "Principal Amount": "principal_amount",
    "Interest amount": "interest_amount",
    "Total Outstanding": "total_outstanding",
    "DUE DATE": "due_date",
    "DPD": "dpd",
    "Agreement No": "agreement_no",
}

MUTHOOT_TRANS_MAPPING = {
    "Loan Reference Number": "loan_reference_number",
    "Tranche Creation Month": "tranche_creation_month",
    "Tranche Creation Date": "tranche_creation_date",
    "Disbursement Month": "disbursement_month",
    "Disbursement Date": "disbursement_date",
    "Loan Account Number": "loan_account_number",
    "Anchor Name": "anchor_name",
    "Borrower Name": "borrower_name",
    "Invoice Date": "invoice_date",
    "Invoice Number": "invoice_number",
    "Invoice Amount(in Rs.)": "invoice_amount_in_rs",
    "Principal Amount(in Rs.)": "principal_amount_in_rs",
    "Net Disbursement Amount(in Rs.)": "net_disbursement_amount_in_rs",
    "Eligibility(%)": "eligibility",
    "Disbursement UTR": "disbursement_utr",
    "Beneficiary Account Name": "beneficiary_account_name",
    "Beneficiary Account Number": "beneficiary_account_number",
    "Beneficiary IFSC": "beneficiary_ifsc",
    "Due Date": "due_date",
    "Tranche Tenure(in Days)": "tranche_tenure_in_days",
    "Interest Type": "interest_type",
    "Interest % and Borne By": "interest_and_borne_by",
    "Interest & Penal Accrual Till Date(in Rs.)": "interest_penal_accrual_till_date_in_rs",
    "Interest Accrual Till Date(in Rs.)": "interest_accrual_till_date_in_rs",
    "Penal Accrual Till Date(in Rs.)": "penal_accrual_till_date_in_rs",
    "Principal Repayment(in Rs.)": "principal_repayment_in_rs",
    "Interest Repayment(in Rs.)": "interest_repayment_in_rs",
    "Penal Repayment(in Rs.)": "penal_repayment_in_rs",
    "Total Repayment(in Rs.)": "total_repayment_in_rs",
    "Latest Repayment Date": "latest_repayment_date",
    "Principal Outstanding(in Rs.)": "principal_outstanding_in_rs",
    "Interest Outstanding(in Rs.)": "interest_outstanding_in_rs",
    "Penal Outstanding(in Rs.)": "penal_outstanding_in_rs",
    "Total Outstanding(in Rs.)": "total_outstanding_in_rs",
    "Interest DPD": "interest_dpd",
    "Interest DPD Bucket": "interest_dpd_bucket",
    "Tranche Interest Status": "tranche_interest_status",
    "Maturing Days": "maturing_days",
    "Principal DPD": "principal_dpd",
    "Principal DPD Bucket": "principal_dpd_bucket",
    "Tranche Principal Status": "tranche_principal_status",
    "Principal Overdue(in Rs.)": "principal_overdue_in_rs",
    "Tranche Closure Date": "tranche_closure_date",
    "Tranche Level DPD": "tranche_level_dpd",
    "Tranche Level DPD Bucket": "tranche_level_dpd_bucket",
    "Tranche Final Status": "tranche_final_status",
    "Total Overdue(in Rs.)": "total_overdue_in_rs",
    "Borrower Repayment Virtual Account Number": "borrower_repayment_virtual_account_number",
    "Anchor Repayment Virtual Account Number": "anchor_repayment_virtual_account_number",
    "Repayment IFSC": "repayment_ifsc",
    "Repayment Account Type": "repayment_account_type",
    "Repayment Bank Name": "repayment_bank_name",
}

KOTAK_HWC_CREDIT_MAPPING = {
    "Dealer Name": "dealer_name",
    "Sanction Limit": "sanction_limit",
    "Operative Limit": "operative_limit",
    "Utilised Limit": "utilised_limit",
    "Overdue": "overdue",
    "DPD": "dpd",
    "OD Outstanding": "od_outstanding",
    "Available Limit": "available_limit",
    "Interest": "interest",
    "Distributor Code": "distributor_code",
}

KOTAK_CKPL_CREDIT_MAPPING = {
    "Dealer Name": "dealer_name",
    "Sanction Limit": "sanction_limit",
    "Operative Limit": "operative_limit",
    "Utilised Limit": "utilised_limit",
    "Overdue": "overdue",
    "DPD": "dpd",
    "Available Limit": "available_limit",
    "Interest": "interest",
    "Distributor Code": "distributor_code"
}

TCPL_CREDIT_MAPPING = {
    "Customer ID": "customer_id",
    "Account ID": "account_id",
    "Client Name": "client_name",
    "Program ID": "program_id",
    "Program Name": "program_name",
    "Product Name": "product_name",
    "Sanction Limit": "sanction_limit",
    "Max Active Drawdowns": "max_active_drawdowns",
    "Utilized Limit": "utilized_limit",
    "Available Limit": "available_limit",
    "Limit Setup Date": "limit_setup_date",
    "Expiry Date": "expiry_date",
    "Adhoc Available Limit": "adhoc_available_limit",
    "Adhoc Activation Date": "adhoc_activation_date",
    "Adhoc Line Expiry Date": "adhoc_line_expiry_date",
    "Status": "status",
    "RM Name": "rm_name",
    "Distributor Code": "distributor_code"
}

HERO_CREDIT_MAPPING = {
    "Sr. No": "sr_no",
    "LAN No": "lan_no",
    "Customer Name": "customer_name",
    "Account Limit": "account_limit",
    "Limit Utilization (Utilized amount)": "limit_utilization_utilized_amount",
    "Limit Available": "limit_available",
    "Limit Utilized (In percentage)": "limit_utilized_in_percentage",
    "Deal Expiry Date": "deal_expiry_date",
    "Beneficiary Name": "beneficiary_name",
    "Beneficiary Account No": "beneficiary_account_no",
    "DPD": "dpd",
    "Distributor Code": "distributor_code"
}

MUTHOOT_CREDIT_MAPPING = {
    "Loan Account Number": "loan_account_number",
    "Borrower Name": "borrower_name",
    "Sanctioned Limit": "sanctioned_limit",
    "Available Limit": "available_limit",
    "Distributor Code": "distributor_code"
}

CONSOLIDATED_LIMIT_MAPPING = {
    "Sno": "sno",
    "Company Name": "company_name",
    "Distributor Code": "distributor_code",
    "City": "city",
    "State": "state",
    "Lender": "lender",
    "Sanction Limit": "sanction_limit",
    "Operative Limit": "operative_limit",
    "Utilised Limit": "utilised_limit",
    "Available Limit": "available_limit",
    "Limit Expiry": "limit_expiry",
    "Overdue": "overdue",
    "Funding Type": "funding_type",
    "Billing Status": "billing_status",
    "Anchor Id": "anchor_id",
    "Distributor Phone": "distributor_phone",
    "Distributor Email": "distributor_email",
}

#mandatory fields for all the modules
DIST_MASTER_MANDATORY_FIELDS = [
    "Anchor",
    "Data Received",
    "Distributor Code",
    "Distributor Name",
    "City",
    "State",
]

INVOICE_MASTER_MANDATORY_FIELDS = [
    "Anchor",
    "Processed by",
    "Working Date",
    "Lender Name",
    "Distributor Name",
    "Distributor code",
    "Beneficiary Name",
    "Beneficiary A/c no",
    "Bank Name",
    "IFSC Code",
    "Branch",
    "Invoice no",
    "Invoice amount",
    "Invoice date",
    "Loan Amount",
    "Loan Disbursement date",
    "Status",
    "Status Reason",
]

KOTAK_HWC_TRANS_MANDATORY_FIELDS = [
    "Dealer Name",
    "Invoice Number",
]

KOTAK_CKPL_TRANS_MANDATORY_FIELDS = [
    "Dealer Name",
    "Invoice Number",
]

TCPL_TRANS_MANDATORY_FIELDS = [
    "Customer Name",
    "Invoice No",
]

HERO_TRANS_MANDATORY_FIELDS = [
    "Client Name",
    "Invoice Number",
]

MUTHOOT_TRANS_MANDATORY_FIELDS = [
    "Borrower Name",
    "Invoice Number",
]

KOTAK_HWC_CREDIT_MANDATORY_FIELDS = [
    "Dealer Name",
    "Sanction Limit",
    "Operative Limit",
    "Utilised Limit",
    "Overdue",
    "DPD",
    "Available Limit",
    "Interest",
    "Distributor Code",
]

KOTAK_CKPL_CREDIT_MANDATORY_FIELDS = [
    "Dealer Name",
    "Sanction Limit",
    "Operative Limit",
    "Utilised Limit",
    "Overdue",
    "DPD",
    "Available Limit",
    "Interest",
    "Distributor Code",
]

TCPL_CREDIT_MANDATORY_FIELDS = []

HERO_CREDIT_MANDATORY_FIELDS = [
    "Customer Name",
    "Account Limit",
    "Limit Utilization (Utilized amount)",
    "Limit Available",
    "Deal Expiry Date",
    "DPD",
    "Distributor Code",
]

MUTHOOT_CREDIT_MANDATORY_FIELDS = [
    "Borrower Name",
    "Sanctioned Limit",
    "Available Limit",
    "Distributor Code",
]

CONSOLIDATED_LIMIT_MANDATORY_FIELDS = [
    "Sno",
    "Company Name",
    "Distributor Code",
    "City",
    "State",
    "Lender",
    "Sanction Limit",
    "Operative Limit",
    "Utilised Limit",
    "Available Limit",
    "Limit Expiry",
    "Overdue",
    "Funding Type",
    "Billing Status",
    "Anchor Id",
    "Distributor Phone",
    "Distributor Email",
]