DIST_HEADER_MAPPING = {
    "Anchor": "anchor",
    "Data Received": "data_received",
    "Enrollment Date": "enrollment_date",
    "Distributor Code": "distributor_code",
    "Distributor Name": "distributor_name",
    "CFA Name":"cfa_name",
    "Region": "region",
    "Division": "division",
    "City": "city",
    "State": "state",
    "Pincode": "pincode",
    "Distribution Type":"distribution_type",
    "Leap/Non Leap":"leap_non_leap",
    "Email Id":"email",
    "Mobile No":"mobile_number",
    "Phone No":"phone_number",
    "GST Number":"gst_number",
    "PAN Number":"pan_number",
    # "Sales Month 1":"sales_month_1",
    # "Sales Month 2":"sales_month_2",
    # "Sales Month 3":"sales_month_3",
    # "Sales Month 4":"sales_month_4",
    # "Sales Month 5":"sales_month_5",
    # "Sales Month 6":"sales_month_6",
    # "Sales Month 7":"sales_month_7",
    # "Sales Month 8":"sales_month_8",
    # "Sales Month 9":"sales_month_9",
    # "Sales Month 9":"sales_month_9",
    # "Sales Month 10":"sales_month_10",
    # "Sales Month 11":"sales_month_12",
}

INVOICE_HEADER_MAPPING = {
    "Anchor": "anchor",
    "Processed by": "processed_by",
    "Working Date": "working_date",
    "Invoice Received Date": "invoice_received_date",
    "Received time": "received_time",
    "Loan type": "loan_type",
    "Lender Name": "lender_name",
    "Distributor Name": "distributor_name",
    "Distributor code": "distributor_code",
    "Contact Number": "contact_number",
    "Email ID": "email_id",
    "Himalaya CFA": "himalaya_cfa",
    "Beneficiary Name": "beneficiary_name",
    "Beneficiary A/c no": "beneficiary_a_c_no",
    "Bank Name": "bank_name",
    "IFSC Code": "ifsc_code",
    "Branch": "branch",
    "Invoice no": "invoice_no",
    "Invoice amount": "invoice_amount",
    "Invoice date": "invoice_date",
    "Loan Amount": "loan_amount",
    "Loan Disbursement date": "loan_disbursement_date",
    "Aging": "aging",
    "Tenure": "tenure",
    "UTR": "utr",
    "Status": "status",
    "Status Reason": "status_reason",
    "Comments": "comments",
}